// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_EC1;

namespace Proyecto_EC1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221008151446_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto_EC1.Entitys.Categoria", b =>
                {
                    b.Property<int>("Id_catg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DESP_CATG")
                        .HasColumnType("bit");

                    b.Property<string>("NOM_CATG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_catg");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Cita", b =>
                {
                    b.Property<int>("id_cita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("fecha")
                        .HasColumnType("int");

                    b.HasKey("id_cita");

                    b.HasIndex("ClienteId_Cliente");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fech_nac")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ruc")
                        .HasColumnType("int");

                    b.Property<int>("tip_doc")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioId_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Cliente");

                    b.HasIndex("usuarioId_Usuario");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Detalle_pedido", b =>
                {
                    b.Property<int>("Id_dped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_pedido")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("Id_prod")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId_pedido")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId_prod")
                        .HasColumnType("int");

                    b.Property<int>("cant")
                        .HasColumnType("int");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.Property<string>("producto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("subtotal")
                        .HasColumnType("real");

                    b.Property<int>("und")
                        .HasColumnType("int");

                    b.HasKey("Id_dped");

                    b.HasIndex("PedidoId_pedido");

                    b.HasIndex("ProductoId_prod");

                    b.ToTable("Detalle_pedido");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Factura", b =>
                {
                    b.Property<int>("Id_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("importe")
                        .HasColumnType("int");

                    b.HasKey("Id_Factura");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Pedido", b =>
                {
                    b.Property<int>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Id_cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Id_factura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("facturaId_Factura")
                        .HasColumnType("int");

                    b.Property<int>("fech_entr")
                        .HasColumnType("int");

                    b.Property<int>("fech_ped")
                        .HasColumnType("int");

                    b.Property<int>("hor_entr")
                        .HasColumnType("int");

                    b.Property<int>("hor_ped")
                        .HasColumnType("int");

                    b.Property<int>("num_ped")
                        .HasColumnType("int");

                    b.Property<string>("obs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_pedido");

                    b.HasIndex("ClienteId_Cliente");

                    b.HasIndex("facturaId_Factura");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Producto", b =>
                {
                    b.Property<int>("Id_prod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaId_catg")
                        .HasColumnType("int");

                    b.Property<bool>("NOM_PROD")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.Property<bool>("PREC_PROD")
                        .HasColumnType("bit");

                    b.Property<bool>("STOCK_PROD")
                        .HasColumnType("bit");

                    b.HasKey("Id_prod");

                    b.HasIndex("CategoriaId_catg");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Cita", b =>
                {
                    b.HasOne("Proyecto_EC1.Entitys.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Cliente", b =>
                {
                    b.HasOne("Proyecto_EC1.Entitys.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId_Usuario");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Detalle_pedido", b =>
                {
                    b.HasOne("Proyecto_EC1.Entitys.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId_pedido");

                    b.HasOne("Proyecto_EC1.Entitys.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId_prod");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Pedido", b =>
                {
                    b.HasOne("Proyecto_EC1.Entitys.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId_Cliente");

                    b.HasOne("Proyecto_EC1.Entitys.Factura", "factura")
                        .WithMany()
                        .HasForeignKey("facturaId_Factura");

                    b.Navigation("Cliente");

                    b.Navigation("factura");
                });

            modelBuilder.Entity("Proyecto_EC1.Entitys.Producto", b =>
                {
                    b.HasOne("Proyecto_EC1.Entitys.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId_catg");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
